import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import profileImage from "../public/p2.png";
import profileDesign from "../public/design.png";
import profileCode from "../public/code.png";
import portfolio1 from "../public/web1.png";
import portfolio2 from "../public/web2.png";
import portfolio3 from "../public/web3.png";
import portfolio4 from "../public/web4.png";
import portfolio5 from "../public/web5.png";

import { motion,  useScroll } from "framer-motion";


import {BsFillMoonStarsFill, BsGithub, BsFacebook, BsLinkedin} from "react-icons/bs";

import { useState } from 'react';
const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [darkMode ,setdarkMode] = useState(false);
  const { scrollYProgress } = useScroll();

  
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>My portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,400;0,500;0,600;0,800;1,100&display=swap');
        </style>
      </Head>
      <main className='font-poppins min-h-screen px-10 bg-sky-100 md:px-20 lg:px-40 dark:bg-gray-800'>
        <section>
          <nav className='py-10 flex justify-between'>
            <h1 className=' text-sm opacity-40 dark:text-white'>Next JS  Practice project</h1>
            <ul className='flex items-center'>
              <li>
                  <BsFillMoonStarsFill
                  onClick={()=> setdarkMode(!darkMode)}
                  className=' cursor-pointer mx-5 md:text-2xl dark:text-white'
                   />
              </li>
              <li>
                <a 
                  className=' bg-sky-500 px-4 py-1 border-none rounded-md'
                  href="https://github.com/minudaSaswitha" target={'_blank'}>Follow</a>
              </li>
            </ul>
          </nav>
          <div className=' text-center p-10'>
            
            <h1 className=' text-5xl font-bold text-sky-500 lg:mb-3 lg:text-8xl'>Minuda saswitha</h1>
             <h3 className=' text-sm font-bold py-5 md:text-2xl dark:text-white'>Learning Web development</h3>
             <p className=' text-sm text-gray-500 leading-6 max-w-xl mx-auto  md:text-md '>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia eum quos aut impedit quas libero, laboriosam, consequatur praesentium voluptates alias, cupiditate possimus! A distinctio cum rem id ratione. Soluta, quia.</p>
          </div>
          <div className='flex text-5xl justify-center gap-10 text-gray-400'>
              <a href="https://github.com/minudaSaswitha">
                <BsGithub />
                </a>
              <a href="https://web.facebook.com/profile.php?id=100088955572785">
                < BsFacebook />
                </a>
              <a href="https://www.linkedin.com/in/minuda-saswitha-718141265/">
                < BsLinkedin />
                </a>
          </div>
          <motion.div 
          
          initial={{ x: -2,
           
           opacity:0.5,
           scale: 0.5,
           rotate: 0,}}
           animate={{ x: 0,
           
             opacity:1,
             scale: 1,
             rotate: 0,}}
             transition={{duration: 0.5}}
         >
          <div className=' m-auto relative bg-gradient-to-b from-sky-300 w-80 h-80 p-5 mt-20 rounded-full'>

        <Image
              src={profileImage} alt="Profie"
              layout='fill' objectFit='cover'
              className='item'
          />
        
          
          </div>
          </motion.div>
        </section>
        <section>
          <div>
            <h2 className='text-5xl py-10 font-bold opacity-60 dark:text-white'>Skills</h2>
            <p className=' text-sm text-gray-500 leading-6 dark:text-white'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vel voluptates atque alias repudiandae quisquam modi numquam aliquid cupiditate illo earum ratione repellat quod assumenda ipsum sapiente quis, officia quos commodi?</p>
          </div>
          <div className='md:flex lg:flex gap-10 mx-auto'>
            <motion.div
            whileHover={{scale:1.1}} 
            whileTap={{scale:0.9}}
            >
            <div className=' bg-sky-300 text-center shadow-sm p-5 rounded-xl my-10'>
              <Image src={profileDesign} alt='image' width={100} height={100} 
              className=" inline"
              />
              <h2 className='text-2xl font-bold'>Graphic Designing</h2>
              <p className='text-sm py-2 text-gray-800 leading-6'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iure fuga distinctio beatae</p>
            </div>
            </motion.div>
            <motion.div
            whileHover={{scale:1.1}} 
            whileTap={{scale:0.9}}
            >
            <div  className=' bg-sky-300 text-center shadow-sm p-5 rounded-xl my-10'>
              <Image src={profileCode} alt='' width={100} height={100} 
              className=" inline" />
              <h2 className='text-2xl font-bold'>Web Development</h2>
              <p className='text-sm py-2 text-gray-800 leading-6'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iure fuga distinctio beatae</p>
            </div>
            </motion.div>
            <motion.div
            whileHover={{scale:1.1}} 
            whileTap={{scale:0.9}}
            >
            <div className=' bg-sky-300 text-center shadow-sm p-5 rounded-xl my-10'>
              <Image src={profileDesign} alt='image' width={100} height={100} 
              className=" inline"
              />
              <h2 className='text-2xl font-bold'>Graphic Designing</h2>
              <p className='text-sm py-2 text-gray-800 leading-6'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iure fuga distinctio beatae</p>
            </div>
            </motion.div>
           
          </div>
        </section>
        <section>
            <div>
              <h2 className='text-5xl py-10 font-bold opacity-60 dark:text-white'>Portfolio</h2>
              <p className=' text-sm text-gray-500 leading-6 dark:text-white'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia eum quos aut impedit quas libero, laboriosam, consequatur praesentium voluptates alias, cupiditate possimus! A distinctio cum rem id ratione. Soluta, quia.</p>
            </div>
            <div className='flex flex-col gap-10 p-10 lg:flex-row lg:flex-wrap'>
              <div className=' basis-1/3 flex-1'>
                <motion.div
                whileHover={{scale:1.1, rotate:3}}
                whileTap={{scale:0.8, rotate:-10}}
                >
              <Image src={portfolio1} alt='img1' layout='responsive'
              className='rounded-lg object-cover' />
              </motion.div>
              </div>
              <div className=' basis-1/3 flex-1'>
              <motion.div
                whileHover={{scale:1.1, rotate:3}}
                whileTap={{scale:0.8, rotate:-10}}
                >
               <Image src={portfolio2} alt='img1' layout='responsive'
              className='rounded-lg object-cover' />
              </motion.div>
              </div>
              <div className=' basis-1/3 flex-1'>
              <motion.div
                whileHover={{scale:1.1, rotate:3}}
                whileTap={{scale:0.8, rotate:-10}}
                >
               <Image src={portfolio3} alt='img1' layout='responsive'
              className='rounded-lg object-cover' />
              </motion.div>
              </div>
              <div className=' basis-1/3 flex-1'>
              <motion.div
                whileHover={{scale:1.1, rotate:3}}
                whileTap={{scale:0.8, rotate:-10}}
                >
               <Image src={portfolio4} alt='img1' layout='responsive'
              className='rounded-lg object-cover' />
              </motion.div>
              </div>
              <div className=' basis-1/3 flex-1'>
              <motion.div
                whileHover={{scale:1.1, rotate:3}}
                whileTap={{scale:0.8, rotate:-10}}
                >
               <Image src={portfolio5} alt='img1' layout='responsive'
              className='rounded-lg object-cover' />
              </motion.div>
              </div>
              <div className=' basis-1/3 flex-1'>
              <motion.div
                whileHover={{scale:1.1, rotate:3}}
                whileTap={{scale:0.8, rotate:-10}}
                >
               <Image src={portfolio1} alt='img1' layout='responsive'
              className='rounded-lg object-cover' />
              </motion.div>
              </div>
            </div>
        </section>

        <footer className=' border-t-2  border-sky-700 text-sm opacity-60 flex flex-col gap-5 items-center justify-center py-10  lg:items-center'>
          <div>
            <h3 className='text-base mb-2 dark:text-sky-300'>Contact me for more details... </h3>
            <p className=' opacity-50 dark:text-white'>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quae, vel eveniet, quo voluptatibus, non magnam quam assumenda perferendis reprehenderit repellendus fugit. Commodi explicabo optio obcaecati ea odio sapiente iusto tempore.</p>
          </div>
          <div>

          </div>
        </footer>
      </main>
    </div>
  )
}
